FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm
EXPOSE 7860
COPY app.py .
COPY custom_models.py .
COPY .streamlit/config.toml .streamlit/
COPY models/baseline_model_lr2.joblib models/
COPY models/baseline_model_nb2.joblib models/

HEALTHCHECK CMD curl --fail http://localhost:7860/_stcore/health

CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]
